/*
    Edit by Nufus
 */
package view;

import controller.ControllerCustomer;
import controller.ControllerMainMenu;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.*;

/**
 *
 * @author Lenovo
 */
public class GUICustomer extends javax.swing.JFrame {

    /**
     * Creates new form GUICustomer
     */
    private ControllerMainMenu ctrlMM;
    private ControllerCustomer ctrlCs;
    
    public GUICustomer(ControllerMainMenu ctrlMM, Application model) throws SQLException {
        initComponents();
        this.ctrlMM = ctrlMM;
        ctrlCs = new ControllerCustomer(model, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJKReg = new javax.swing.ButtonGroup();
        bgJKUDP = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pRegistrasi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrasiReg = new javax.swing.JButton();
        rbLakiReg = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rbPerempuanReg = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfIdReg = new javax.swing.JTextField();
        tfNamaReg = new javax.swing.JTextField();
        tfUmurReg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamatReg = new javax.swing.JTextArea();
        tfKontakReg = new javax.swing.JTextField();
        pPemesanan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfIdPsnPsn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsPaketWisataPsn = new javax.swing.JList<>();
        btnPesanPsn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tfTglPesanPsn = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfIdCsPsn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfTotalHargaPsn = new javax.swing.JTextField();
        btnGetTHargaPsn = new javax.swing.JButton();
        btnSearchIdCsPsn = new javax.swing.JButton();
        pUbahDataPribadi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnUpdateUDP = new javax.swing.JButton();
        rbLakiUDP = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbPerempuanUDP = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfIdCsUDP = new javax.swing.JTextField();
        btnCariIdCsUDP = new javax.swing.JButton();
        tfNamaUDP = new javax.swing.JTextField();
        tfUmurUDP = new javax.swing.JTextField();
        tfKontakUDP = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAlamatUDP = new javax.swing.JTextArea();
        pLihatPaketWisata = new javax.swing.JPanel();
        spTabelLPW = new javax.swing.JScrollPane();
        tbLPW = new javax.swing.JTable();
        btnRefreshLPW = new javax.swing.JButton();
        pLihatTourGuide = new javax.swing.JPanel();
        spTabelLTG = new javax.swing.JScrollPane();
        tbLTG = new javax.swing.JTable();
        btnRefreshLTG = new javax.swing.JButton();
        pLihatTempatWisata = new javax.swing.JPanel();
        spTabelLTW = new javax.swing.JScrollPane();
        tbLTW = new javax.swing.JTable();
        btnRefreshLTW = new javax.swing.JButton();
        btnBMM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu Customer");

        jLabel3.setText("Nama :");

        btnRegistrasiReg.setText("Registrasi");
        btnRegistrasiReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrasiRegMouseClicked(evt);
            }
        });
        btnRegistrasiReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiRegActionPerformed(evt);
            }
        });

        bgJKReg.add(rbLakiReg);
        rbLakiReg.setText("Laki - Laki");
        rbLakiReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiRegActionPerformed(evt);
            }
        });

        jLabel8.setText("Alamat :");

        bgJKReg.add(rbPerempuanReg);
        rbPerempuanReg.setText("Perempuan");
        rbPerempuanReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanRegActionPerformed(evt);
            }
        });

        jLabel9.setText("Kontak :");

        jLabel10.setText("Jenis Kelamin :");

        jLabel11.setText("Umur :");

        jLabel12.setText("ID");

        tfIdReg.setEditable(false);
        tfIdReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdRegActionPerformed(evt);
            }
        });

        taAlamatReg.setColumns(20);
        taAlamatReg.setRows(5);
        jScrollPane1.setViewportView(taAlamatReg);

        javax.swing.GroupLayout pRegistrasiLayout = new javax.swing.GroupLayout(pRegistrasi);
        pRegistrasi.setLayout(pRegistrasiLayout);
        pRegistrasiLayout.setHorizontalGroup(
            pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistrasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUmurReg)
                                .addComponent(tfNamaReg)
                                .addComponent(tfIdReg, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addGroup(pRegistrasiLayout.createSequentialGroup()
                                    .addComponent(rbLakiReg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbPerempuanReg))
                                .addComponent(tfKontakReg))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(298, 298, 298))
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addComponent(btnRegistrasiReg)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pRegistrasiLayout.setVerticalGroup(
            pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistrasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfIdReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rbPerempuanReg)
                    .addComponent(rbLakiReg))
                .addGap(11, 11, 11)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfUmurReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfKontakReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(19, 19, 19)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 111, Short.MAX_VALUE))
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrasiReg)
                        .addGap(32, 32, 32))))
        );

        jTabbedPane1.addTab("Registrasi", pRegistrasi);

        jLabel14.setText("Id Pemesanan");

        tfIdPsnPsn.setEditable(false);
        tfIdPsnPsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdPsnPsnActionPerformed(evt);
            }
        });

        jLabel15.setText("Paket Wisata");

        jScrollPane2.setViewportView(lsPaketWisataPsn);

        btnPesanPsn.setText("Pesan");
        btnPesanPsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanPsnActionPerformed(evt);
            }
        });

        jLabel17.setText("Tanggal Pesan");

        jLabel18.setText("Id Anda");

        tfIdCsPsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdCsPsnActionPerformed(evt);
            }
        });

        jLabel16.setText("Total Harga");

        tfTotalHargaPsn.setEditable(false);

        btnGetTHargaPsn.setText("refresh");
        btnGetTHargaPsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTHargaPsnActionPerformed(evt);
            }
        });

        btnSearchIdCsPsn.setText("Search");

        javax.swing.GroupLayout pPemesananLayout = new javax.swing.GroupLayout(pPemesanan);
        pPemesanan.setLayout(pPemesananLayout);
        pPemesananLayout.setHorizontalGroup(
            pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesanPsn)
                    .addGroup(pPemesananLayout.createSequentialGroup()
                        .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfIdPsnPsn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(tfIdCsPsn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchIdCsPsn))
                    .addGroup(pPemesananLayout.createSequentialGroup()
                        .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTotalHargaPsn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(tfTglPesanPsn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetTHargaPsn)))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        pPemesananLayout.setVerticalGroup(
            pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPemesananLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfIdCsPsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchIdCsPsn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfIdPsnPsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfTotalHargaPsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetTHargaPsn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfTglPesanPsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPesanPsn)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pemesanan", pPemesanan);

        jLabel2.setText("Nama :");

        btnUpdateUDP.setText("Update");
        btnUpdateUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUDPActionPerformed(evt);
            }
        });

        bgJKUDP.add(rbLakiUDP);
        rbLakiUDP.setText("Laki - Laki");
        rbLakiUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiUDPActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat :");

        bgJKUDP.add(rbPerempuanUDP);
        rbPerempuanUDP.setText("Perempuan");
        rbPerempuanUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanUDPActionPerformed(evt);
            }
        });

        jLabel7.setText("Kontak :");

        jLabel4.setText("Jenis Kelamin :");

        jLabel5.setText("Umur :");

        jLabel13.setText("ID :");

        btnCariIdCsUDP.setText("Cari ID");
        btnCariIdCsUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariIdCsUDPActionPerformed(evt);
            }
        });

        tfNamaUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaUDPActionPerformed(evt);
            }
        });

        tfKontakUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKontakUDPActionPerformed(evt);
            }
        });

        taAlamatUDP.setColumns(20);
        taAlamatUDP.setRows(5);
        jScrollPane3.setViewportView(taAlamatUDP);

        javax.swing.GroupLayout pUbahDataPribadiLayout = new javax.swing.GroupLayout(pUbahDataPribadi);
        pUbahDataPribadi.setLayout(pUbahDataPribadiLayout);
        pUbahDataPribadiLayout.setHorizontalGroup(
            pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateUDP)
                    .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                        .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(49, 49, 49)
                        .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                                .addComponent(rbLakiUDP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPerempuanUDP))
                            .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfNamaUDP)
                                        .addComponent(tfUmurUDP, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfKontakUDP, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(tfIdCsUDP))
                                .addGap(30, 30, 30)
                                .addComponent(btnCariIdCsUDP))))
                    .addComponent(jLabel7))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        pUbahDataPribadiLayout.setVerticalGroup(
            pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfIdCsUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariIdCsUDP))
                .addGap(9, 9, 9)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbLakiUDP)
                    .addComponent(rbPerempuanUDP))
                .addGap(11, 11, 11)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfUmurUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfKontakUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnUpdateUDP)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Ubah Data Pribadi", pUbahDataPribadi);

        tbLPW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Harga", "List Guide", "List Tujuan", "Tgll Berangkat", "Tgl Pulang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTabelLPW.setViewportView(tbLPW);

        btnRefreshLPW.setText("refresh");
        btnRefreshLPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshLPWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLihatPaketWisataLayout = new javax.swing.GroupLayout(pLihatPaketWisata);
        pLihatPaketWisata.setLayout(pLihatPaketWisataLayout);
        pLihatPaketWisataLayout.setHorizontalGroup(
            pLihatPaketWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatPaketWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLihatPaketWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTabelLPW, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(pLihatPaketWisataLayout.createSequentialGroup()
                        .addComponent(btnRefreshLPW)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pLihatPaketWisataLayout.setVerticalGroup(
            pLihatPaketWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatPaketWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLPW, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshLPW)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lihat Paket Wisata", pLihatPaketWisata);

        tbLTG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Umur", "Jenis Kelamin", "Alamat", "Kontak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTabelLTG.setViewportView(tbLTG);

        btnRefreshLTG.setText("refresh");
        btnRefreshLTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshLTGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLihatTourGuideLayout = new javax.swing.GroupLayout(pLihatTourGuide);
        pLihatTourGuide.setLayout(pLihatTourGuideLayout);
        pLihatTourGuideLayout.setHorizontalGroup(
            pLihatTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatTourGuideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLihatTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTabelLTG, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(pLihatTourGuideLayout.createSequentialGroup()
                        .addComponent(btnRefreshLTG)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pLihatTourGuideLayout.setVerticalGroup(
            pLihatTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatTourGuideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLTG, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshLTG)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lihat Tour Guide", pLihatTourGuide);

        tbLTW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Alamat", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTabelLTW.setViewportView(tbLTW);

        btnRefreshLTW.setText("refresh");
        btnRefreshLTW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshLTWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLihatTempatWisataLayout = new javax.swing.GroupLayout(pLihatTempatWisata);
        pLihatTempatWisata.setLayout(pLihatTempatWisataLayout);
        pLihatTempatWisataLayout.setHorizontalGroup(
            pLihatTempatWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatTempatWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLihatTempatWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTabelLTW, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(pLihatTempatWisataLayout.createSequentialGroup()
                        .addComponent(btnRefreshLTW)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pLihatTempatWisataLayout.setVerticalGroup(
            pLihatTempatWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatTempatWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLTW, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefreshLTW)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lihat Tempat Wisata", pLihatTempatWisata);

        btnBMM.setText("Back to Main Menu");
        btnBMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBMMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(153, 153, 153)
                        .addComponent(btnBMM))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBMM)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUDPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnUpdateUDPActionPerformed

    private void rbLakiUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiUDPActionPerformed

    private void rbPerempuanUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanUDPActionPerformed

    private void btnRegistrasiRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiRegActionPerformed
        //if error JOptionPane.showMessageDialog(null, "Hello!");
        
    }//GEN-LAST:event_btnRegistrasiRegActionPerformed

    private void rbLakiRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiRegActionPerformed

    private void rbPerempuanRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanRegActionPerformed

    private void tfIdRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdRegActionPerformed

    private void btnPesanPsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanPsnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPesanPsnActionPerformed

    private void tfIdCsPsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdCsPsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdCsPsnActionPerformed

    private void tfIdPsnPsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdPsnPsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdPsnPsnActionPerformed

    private void btnCariIdCsUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariIdCsUDPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCariIdCsUDPActionPerformed

    private void tfNamaUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaUDPActionPerformed

    private void btnBMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBMMActionPerformed
        ctrlMM.toMainMenu();
    }//GEN-LAST:event_btnBMMActionPerformed

    private void btnGetTHargaPsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTHargaPsnActionPerformed
        
    }//GEN-LAST:event_btnGetTHargaPsnActionPerformed

    private void btnRefreshLPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshLPWActionPerformed
        
    }//GEN-LAST:event_btnRefreshLPWActionPerformed

    private void btnRefreshLTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshLTGActionPerformed
        
    }//GEN-LAST:event_btnRefreshLTGActionPerformed

    private void btnRefreshLTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshLTWActionPerformed
        
    }//GEN-LAST:event_btnRefreshLTWActionPerformed

    private void btnRegistrasiRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrasiRegMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrasiRegMouseClicked

    private void tfKontakUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKontakUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKontakUDPActionPerformed
    
    //TAB REGISTRASI
    //GETTER
    public JTextField getTfIdReg (){
        return tfIdReg;
    }
    public JTextField getTfNamaReg (){
        return tfNamaReg;
    }
    public String getJKReg(){
        if(rbLakiReg.isSelected()){
            return "Laki-Laki";
        }else{
            return "Perempuan";
        }
    }
    public ButtonGroup getBgJKReg(){
        return bgJKReg;
    }
    public JTextField getTfUmurReg (){
        return tfUmurReg;
    }
    public JTextField getTfKontakReg (){
        return tfKontakReg;
    }
    public JTextArea getTaAlamatReg (){
        return taAlamatReg;
    }
    public JButton getBtnRegistrasiReg(){
        return btnRegistrasiReg;
    }
    
    //TAB PEMESANAN
    //GETTER
    public JTextField getTfIdCsPsn(){
        return tfIdCsPsn;
    }
    public JTextField getTfIdPsnPsn (){
        return tfIdPsnPsn;
    }
    public JList<String> getLsPaketWisataPsn (){
        return lsPaketWisataPsn;
    }
    public JTextField getTfTotalHargaPsn(){
        return tfTotalHargaPsn;
    }
    public JTextField getTfTglPesanPsn(){
        return tfTglPesanPsn;
    }
    public JButton getBtnSearchIdCsPsn(){
        return btnSearchIdCsPsn;
    }
    public JButton getBtnGetTHargaPsn(){
        return btnGetTHargaPsn;
    }
    public JButton getBtnPesanPsn(){
        return btnPesanPsn;
    }

    
    //TAB UBAH DATA PRIBADI
    //GETTER
    public JTextField getTfIdCsUDP (){
        return tfIdCsUDP;
    }
    public JTextField getTfNamaUDP (){
        return tfNamaUDP;
    }
    public JRadioButton getRbLakiUDP(){
        return rbLakiUDP;
    }
    public JRadioButton getRbPerempuanUDP(){
        return rbPerempuanUDP;
    }
    public ButtonGroup getBgJKUDP(){
        return bgJKUDP;
    }
    public String getJKUDP(){
        if(rbLakiUDP.isSelected()){
            return "Laki-Laki";
        }else{
            return "Perempuan";
        }
    }
    public JTextField getTfUmurUDP (){
        return tfUmurUDP;
    }
    public JTextArea getTaAlamatUDP (){
        return taAlamatUDP;
    }
    public JTextField getTfKontakUDP (){
        return tfKontakUDP;
    }
    public JButton getBtnCariIdCsUDP(){
        return btnCariIdCsUDP;
    }
    public JButton getBtnUpdateUDP(){
        return btnUpdateUDP;
    }
    
    
    
    
    
    
    //TAB LIHAT PAKET WISATA
    //GETTER
    public JTable getTbLPW (){
        return tbLPW;
    }
    public JButton getBtnRefreshLPW(){
        return btnRefreshLPW;
    }
    //TAB LIHAT TOUR GUIDE
    //GETTER
    public JTable getTbLTG (){
        return tbLTG;
    }
    public JButton getBtnRefreshLTG(){
        return btnRefreshLTG;
    }
    
    //TAB LIHAT TEMPAT WISATA
    //GETTER
    public JTable getTbLTW (){
        return tbLTW;
    }
    public JButton getBtnRefreshLTW(){
        return btnRefreshLTW;
    }
    
    public void addMouseListener(MouseAdapter ma){
        btnRegistrasiReg.addMouseListener(ma);
        btnSearchIdCsPsn.addMouseListener(ma);
        btnPesanPsn.addMouseListener(ma);
        btnGetTHargaPsn.addMouseListener(ma);
        btnCariIdCsUDP.addMouseListener(ma);
        btnUpdateUDP.addMouseListener(ma);
        btnRefreshLPW.addMouseListener(ma);
        btnRefreshLTG.addMouseListener(ma);
        btnRefreshLTW.addMouseListener(ma);
        tbLPW.addMouseListener(ma);                
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJKReg;
    private javax.swing.ButtonGroup bgJKUDP;
    private javax.swing.JButton btnBMM;
    private javax.swing.JButton btnCariIdCsUDP;
    private javax.swing.JButton btnGetTHargaPsn;
    private javax.swing.JButton btnPesanPsn;
    private javax.swing.JButton btnRefreshLPW;
    private javax.swing.JButton btnRefreshLTG;
    private javax.swing.JButton btnRefreshLTW;
    private javax.swing.JButton btnRegistrasiReg;
    private javax.swing.JButton btnSearchIdCsPsn;
    private javax.swing.JButton btnUpdateUDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lsPaketWisataPsn;
    private javax.swing.JPanel pLihatPaketWisata;
    private javax.swing.JPanel pLihatTempatWisata;
    private javax.swing.JPanel pLihatTourGuide;
    private javax.swing.JPanel pPemesanan;
    private javax.swing.JPanel pRegistrasi;
    private javax.swing.JPanel pUbahDataPribadi;
    private javax.swing.JRadioButton rbLakiReg;
    private javax.swing.JRadioButton rbLakiUDP;
    private javax.swing.JRadioButton rbPerempuanReg;
    private javax.swing.JRadioButton rbPerempuanUDP;
    private javax.swing.JScrollPane spTabelLPW;
    private javax.swing.JScrollPane spTabelLTG;
    private javax.swing.JScrollPane spTabelLTW;
    private javax.swing.JTextArea taAlamatReg;
    private javax.swing.JTextArea taAlamatUDP;
    private javax.swing.JTable tbLPW;
    private javax.swing.JTable tbLTG;
    private javax.swing.JTable tbLTW;
    private javax.swing.JTextField tfIdCsPsn;
    private javax.swing.JTextField tfIdCsUDP;
    private javax.swing.JTextField tfIdPsnPsn;
    private javax.swing.JTextField tfIdReg;
    private javax.swing.JTextField tfKontakReg;
    private javax.swing.JTextField tfKontakUDP;
    private javax.swing.JTextField tfNamaReg;
    private javax.swing.JTextField tfNamaUDP;
    private javax.swing.JTextField tfTglPesanPsn;
    private javax.swing.JTextField tfTotalHargaPsn;
    private javax.swing.JTextField tfUmurReg;
    private javax.swing.JTextField tfUmurUDP;
    // End of variables declaration//GEN-END:variables
}
