/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import controller.*;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.*;
/**
 *
 * @author Lenovo
 */
public class GUITourGuide extends javax.swing.JFrame {

    private ControllerMainMenu ctrlMM;
    private ControllerTourGuide ctrlTG;
     private Application model;
    
    public GUITourGuide(ControllerMainMenu ctrlMM, Application model) {
        initComponents();
        this.ctrlMM = ctrlMM;
        ctrlTG = new ControllerTourGuide(model, this);
           this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJKUDP = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pPenugasan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbViewPNGS = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tfIdSearchTGPNGS = new javax.swing.JTextField();
        btnSearchIdTGPNGS = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbLakiUDP = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbPerempuanUDP = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEditUDP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfIdSearchTGUDP = new javax.swing.JTextField();
        btnSearchUDP = new javax.swing.JButton();
        tfNamaUDP = new javax.swing.JTextField();
        tfUmurUDP = new javax.swing.JTextField();
        tfKontakUDP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamatUDP = new javax.swing.JTextArea();
        btnBMM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("TOUR GUIDE MENU");

        tbViewPNGS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paket Wisata", "Tanggal Berangkat", "Tanggal Pulang", "Customer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbViewPNGS);

        jLabel3.setText("Masukkan Id :");

        btnSearchIdTGPNGS.setText("Search");
        btnSearchIdTGPNGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIdTGPNGSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPenugasanLayout = new javax.swing.GroupLayout(pPenugasan);
        pPenugasan.setLayout(pPenugasanLayout);
        pPenugasanLayout.setHorizontalGroup(
            pPenugasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPenugasanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPenugasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                    .addGroup(pPenugasanLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfIdSearchTGPNGS, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchIdTGPNGS)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pPenugasanLayout.setVerticalGroup(
            pPenugasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPenugasanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPenugasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfIdSearchTGPNGS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchIdTGPNGS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PENUGASAN", pPenugasan);

        jPanel2.setRequestFocusEnabled(false);

        jLabel2.setText("Nama :");

        bgJKUDP.add(rbLakiUDP);
        rbLakiUDP.setText("Laki - Laki");
        rbLakiUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiUDPActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat :");

        bgJKUDP.add(rbPerempuanUDP);
        rbPerempuanUDP.setText("Perempuan");
        rbPerempuanUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanUDPActionPerformed(evt);
            }
        });

        jLabel7.setText("Kontak :");

        jLabel4.setText("Jenis Kelamin :");

        jLabel5.setText("Umur :");

        btnEditUDP.setText("Edit Data");
        btnEditUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUDPActionPerformed(evt);
            }
        });

        jLabel8.setText("Masukkan ID");

        btnSearchUDP.setText("search");
        btnSearchUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUDPActionPerformed(evt);
            }
        });

        taAlamatUDP.setColumns(20);
        taAlamatUDP.setRows(5);
        jScrollPane2.setViewportView(taAlamatUDP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbLakiUDP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPerempuanUDP))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfIdSearchTGUDP, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchUDP))
                            .addComponent(tfNamaUDP)
                            .addComponent(tfUmurUDP)
                            .addComponent(tfKontakUDP)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEditUDP))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfIdSearchTGUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchUDP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbLakiUDP)
                    .addComponent(rbPerempuanUDP))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfUmurUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfKontakUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnEditUDP)
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("Ubah Data Pribadi", jPanel2);

        btnBMM.setText("Back to Main Menu");
        btnBMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBMMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(127, 127, 127)
                        .addComponent(btnBMM))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBMM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLakiUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiUDPActionPerformed

    private void rbPerempuanUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanUDPActionPerformed

    private void btnEditUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUDPActionPerformed
        
    }//GEN-LAST:event_btnEditUDPActionPerformed

    private void btnBMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBMMActionPerformed
        ctrlMM.toMainMenu();
    }//GEN-LAST:event_btnBMMActionPerformed

    private void btnSearchUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUDPActionPerformed
        
    }//GEN-LAST:event_btnSearchUDPActionPerformed

    private void btnSearchIdTGPNGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIdTGPNGSActionPerformed
        
    }//GEN-LAST:event_btnSearchIdTGPNGSActionPerformed

    //PAKET WISATA YANG DITUGASKAN
    //GETTER
    public JTextField getTfIdSearchTGPNGS(){
        return tfIdSearchTGPNGS;
    }
    public JTable getTbViewPNGS(){
        return tbViewPNGS;
    }
    public JButton getBtnSearchIdTGPNGS(){
        return btnSearchIdTGPNGS;
    }
    
    //UBAH DATA PRIBADI
    //GETTER
    public JTextField getTfIdSearchTGUDP(){
        return tfIdSearchTGUDP;
    }
    public JTextField getTfNamaUDP(){
        return tfNamaUDP;
    }
    public ButtonGroup getBgJKUDP(){
        return bgJKUDP;
    }
    public JRadioButton getRbLakiUDP(){
        return rbLakiUDP;
    }
    public JRadioButton getRbPerempuanUDP(){
        return rbPerempuanUDP;
    }
    public JTextField getTfUmurUDP(){
        return tfUmurUDP;
    }
    public JTextArea getTaAlamatUDP(){
        return taAlamatUDP;
    }
    public JTextField getTfKontakUDP(){
        return tfKontakUDP;
    }
    public JButton getBtnSearchUDP(){
        return btnSearchUDP;
    }
    public JButton getBtnEditUDP(){
        return btnEditUDP;
    }
    
    public void addMouseListener(MouseAdapter ma){
        btnSearchUDP.addMouseListener(ma);
        btnEditUDP.addMouseListener(ma);
        btnSearchIdTGPNGS.addMouseListener(ma);
        tbViewPNGS.addMouseListener(ma);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJKUDP;
    private javax.swing.JButton btnBMM;
    private javax.swing.JButton btnEditUDP;
    private javax.swing.JButton btnSearchIdTGPNGS;
    private javax.swing.JButton btnSearchUDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pPenugasan;
    private javax.swing.JRadioButton rbLakiUDP;
    private javax.swing.JRadioButton rbPerempuanUDP;
    private javax.swing.JTextArea taAlamatUDP;
    private javax.swing.JTable tbViewPNGS;
    private javax.swing.JTextField tfIdSearchTGPNGS;
    private javax.swing.JTextField tfIdSearchTGUDP;
    private javax.swing.JTextField tfKontakUDP;
    private javax.swing.JTextField tfNamaUDP;
    private javax.swing.JTextField tfUmurUDP;
    // End of variables declaration//GEN-END:variables
}
